name: Shippy Systsems Docker Image CI

on:
  push:
    branches:
      - "main"
      - "local"
  pull_request:
    branches:
      - "main"
      - "local"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shippy/shippy-systems:$(date +%s)
